-- Salon Beheer — MySQL schema voor Hostinger
-- Importeer via phpMyAdmin of api/install.php

CREATE TABLE IF NOT EXISTS salon_meta (
  meta_key VARCHAR(64) NOT NULL PRIMARY KEY,
  meta_value LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_clients (
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_appointments (
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  client_id VARCHAR(80) DEFAULT NULL,
  appt_date DATE DEFAULT NULL,
  appt_time VARCHAR(8) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_client (client_id),
  KEY idx_date (appt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_sync (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO salon_sync (id, revision) VALUES (1, 0);
