-- Salon Beheer — MySQL schema voor Hostinger
-- Importeer via phpMyAdmin of api/install.php

CREATE TABLE IF NOT EXISTS salon_meta (
  meta_key VARCHAR(64) NOT NULL PRIMARY KEY,
  meta_value LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_clients (
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_appointments (
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  client_id VARCHAR(80) DEFAULT NULL,
  appt_date DATE DEFAULT NULL,
  appt_time VARCHAR(8) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_client (client_id),
  KEY idx_date (appt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_sync (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO salon_sync (id, revision) VALUES (1, 0);

CREATE TABLE IF NOT EXISTS salon_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_remember_tokens (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  user_agent VARCHAR(512) NOT NULL DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_token (token_hash),
  KEY idx_user (user_id),
  KEY idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salon_reminder_log (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appointment_id VARCHAR(80) NOT NULL,
  client_id VARCHAR(80) DEFAULT NULL,
  reminder_type VARCHAR(32) NOT NULL DEFAULT '24h',
  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recipient VARCHAR(255) NOT NULL,
  UNIQUE KEY uq_appt_type (appointment_id, reminder_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
